server:
  port: 8100

spring:
  application:
    name: luna-cloud-gateway
  ## GateWay配置
  cloud:
    gateway:
      routes:
        - id: payment_routh_node_1  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: http://127.0.0.1:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider-payment/api/payment/get/**  # 断言，路径相匹配的进行路由

        - id: payment_routh_node_2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: http://127.0.0.1:8001  # 匹配后提供服务的路由地址
          predicates:
            - Path=/provider-payment/api/**  # 断言，路径相匹配的进行路由

# 注册进 eureka Server
eureka:
  instance:
    instance-id: luna-cloud-gateway-node
    prefer-ip-address: true
    # 客户端向服务端发送心跳包
    #lease-renewal-interval-in-seconds: 1
    # 客户端最后一次收到服务端心跳包后的最长等待时间
    #lease-expiration-duration-in-seconds: 3
  client:
    # 注册进 Eureka 的服务中心
    register-with-eureka: true
    # 检索 服务中心 的其它服务
    fetch-registry: true
    service-url:
      # 设置与 Eureka Server 交互的地址
      defaultZone: http://eurekanodei.com:7001/eureka-server/eureka/
      #defaultZone: http://eurekanodeii.com:7002/eureka-server/eureka/,http://eurekanodei.com:7001/eureka-server/eureka/

