server:
  port: 9101
  servlet:
    context-path: /provider-order
spring:
  profiles:
    active: dev
  application:
    name: luna-provider-order
  cloud:
    alibaba:
      seata:
        # 自定义事务组，需要和当时在 seata/conf/file.conf 中的一致
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: f.xicc.cc:23403

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: luna
    password:

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.luna.commons.entities    # 所有Entity别名类所在包


management:
  endpoint:
    health:
      # 展示详细信息
      show-details: always
      # 开启远程关闭
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

# 自定义展示信息
info:
  app:
    name: luna-provider-payment
    java: jdk-1.8
    encodeing: UTF-8
  author: luna
  build:
    artifactId: $project.artifactId$
    version: $project.version$
